name: probe-matrix

on:
  push:
    branches:
      - ci/speed-up-pipeline

permissions:
  contents: read

jobs:
  rustcache-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Probe
        uses: Swatinem/rust-cache@v2
  rustcache-windows:
    runs-on: windows-latest
    steps:
      - name: Probe
        uses: Swatinem/rust-cache@v2
  actionscache-windows:
    runs-on: windows-latest
    steps:
      - name: Probe
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0

